<a href="https://colab.research.google.com/github/pedrofelixrv/Colab/blob/main/AULAS_22_03_%C3%A0_10_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PRIMEIRA AULA - 20/03**

In [443]:
# Atribuindo valores à variáveis.
height = 1.79
weight = 68.7

In [444]:
# Mostrando o valor de uma variável.
weight

68.7

In [445]:
# Utilizando operação de divisão e potenciação com números.
68.7 / 1.79 ** 2

21.44127836209856

In [446]:
# Utilizando operação de divisão e potenciação com as variáveis peso e altura.
weight / height ** 2

21.44127836209856

In [447]:
# Atribuindo o valor da operação de divisão e potenciação à uma variável.
bmi = weight / height ** 2
bmi

21.44127836209856

In [448]:
# Utilizando o comando "print" para mostrar o valor da variável "bmi".
print (bmi)

21.44127836209856


In [449]:
# Utilizando o comando "type" para revelar o tipo da variável. São os tipos: Float ou flutuante, são variáveis que apresentam números decimais.
type (bmi)

float

In [450]:
# Int são o tipo de variáveis que possuem numéros inteiros.
day_of_week = 5
type (day_of_week)

int

In [451]:
# Str ou string, são variáveis que possuem texto.
x = 'body mass index'
y = "this works too"
type (y)

str

In [452]:
# O tipo de variável bool são variaveis que possuem o dois valores, verdadeiro ou falso, nunca uma terceira situação.
z = True
type (z)

bool

In [453]:
# Soma de números inteiro por meio do sinal "+".
2 + 3

5

In [454]:
# Contatenação se trata do ato de unir strings. A seguir, um exemplo de contatenação da string 'ab' mais a string 'cd'.
'ab' + 'cd'

'abcd'

In [455]:
# Também é possivel contatenar variáveis do tipo strin. Nesse caso, a variável A recebe 'ab' e a variável B recebe 'cd' que são contatenadas.
A = 'ab'
B = 'cd'
A + B

'abcd'

In [456]:
# exemplo
print(5/8)

0.625


In [457]:
# soma de 7 com 8
7 + 8

15

In [458]:
# Operação de soma e subtração atribuidas a uma variável.
soma = 5 + 6
print (soma)
subtração = 5 - 6
print (subtração)

11
-1


In [459]:
# Operação de potenciação, multiplicação e resto de divisão atribuidas a uma variável.
pontência = 5 ** 3
multiplicação = 5 * 3
resto_da_divisão = 5 % 3
print (pontência)
print (multiplicação)
print (resto_da_divisão)

125
15
2


In [460]:
# Operação sendo atribuida a uma variável.
rendimento = 100 * 1.1 ** 7
print (rendimento)

194.87171000000012


**SEGUNDA AULA - 22/03**

In [461]:
# Operação realizada com variáveis e contatenação de uma variável com ela mesmo.
savings = 100
growth_multiplier = 1.1
desc = 'compound interest'
year1 = savings * growth_multiplier
print (type(year1))
doubledesc = desc + desc
print (doubledesc)

<class 'float'>
compound interestcompound interest


In [462]:
# Operação de conversão de uma variável do tipo string para uma variável do tipo float.
pi_string = '3.1415926'
pi_float = float (pi_string)
print (type(pi_string))
print (type(pi_float))

<class 'str'>
<class 'float'>


In [463]:
savings = 100
result = 100 * 1.10 ** 2
# print ("I started with" + savings + "and now have" + result + ". Awesome!")

# Não é possível contatenar str com número. Para corrigir o problema, convertemos os números para texto, ou colamos virgulas entre os momentos, separando 'str' de 'int' e 'float'
print ("I started with $" + str(savings) + "and now have $" + str(result) + ". Awesome!")
# ou
print ("I started with $", savings, "and now have $", result, ". Awesome!")

I started with $100and now have $121.00000000000001. Awesome!
I started with $ 100 and now have $ 121.00000000000001 . Awesome!


**TERCEIRA AULA - 28/03**

In [464]:
  # Atribuindo uma lista, que ficam entre colchetes, a uma variável. O que está entre [] e separados por virgula são os elementos dessa lista.
  fam = [1.73, 1.68, 1.71, 1.89]
  fam

[1.73, 1.68, 1.71, 1.89]

In [465]:
# Dentro de uma lista é possível coexistir string, int, float e etc.
fam = ['Pedro', 1.70, 'Cristiane', 1.65, 'Dulce', 1.30, 'Gabriela', 1.55]
fam

['Pedro', 1.7, 'Cristiane', 1.65, 'Dulce', 1.3, 'Gabriela', 1.55]

In [466]:
# Dentro de uma lista é possível que haja outras listas. Nesse exemplo, a lista "fam2" possui outras listas em seu valor, essas sub-listas são separadas por [].
fam2 = [['Pedro', 1.70],
        ['Cristiane', 1.65],
        ['Dulce', 1.30],
        ['Gabriela', 1.55]]
fam2

[['Pedro', 1.7], ['Cristiane', 1.65], ['Dulce', 1.3], ['Gabriela', 1.55]]

In [467]:
# O tipo da varíavel "fam" é "list"
type(fam)

list

In [468]:
type(fam2)

list

In [469]:
# Atribuindo valores a variáveis para criar uma lista a partir delas.
# Áreas dos compartimentos
hall = 14.0
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50
# Criando uma lista com as áreas dos compartimentos
áreas = [hall, kit, liv, bed, bath]
# "Printando" a lista das áreas
print(áreas)
# Adaptando a lista
áreas = 'hallway', hall, 'kitchen', kit, 'living room', liv, 'bedroom', bed, 'bathroom', bath
print(áreas)

[14.0, 18.0, 20.0, 10.75, 9.5]
('hallway', 14.0, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5)


In [470]:
A = [1, 2, 3, 4]
# "A" é uma lista qye possui quatro elementos inteiros
B =[[1, 2, 3], [4, 5, 6]]
# "B" é uma lista na qual possui outras duas lista dentro, sendo cada lista possuindo três elementos inteiros
C = [1 + 2, 'A' * 5, 3]
# "C" é uma lista na qual possui três elementos, sendo o primeiro elemento uma soma de inteiros, o segundo elemento a multiplicação de uma string, e o terceiro elemento um inteiro.

In [471]:
# Lista de listas das áreas dos compartimentos
house = [['hallway', hall],
         ['kitchen', kit],
         ['living room', liv],
         ['bedroom', bed],
         ['bathroom', bath]]
#  "Printando" a lista das lista
print(house)
# "Printando" o tipo da variável "house"
print(type(house))

[['hallway', 14.0], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


In [472]:
# Buscando o segundo elemento da lista "fam"
fam[2]

'Cristiane'

In [473]:
# Buscando o sexto elemento da lista "fam"
fam[6]

'Gabriela'

In [474]:
# Buscando o segundo elemento da lista "house"
house[2]

['living room', 20.0]

In [475]:
# Buscando o terceiro elemento da lista "house"
house[3]

['bedroom', 10.75]

In [476]:
# Buscando o elemento da lista "house" de trás para frente por meio dos números negativos
house[-2]

['bedroom', 10.75]

In [477]:
# Pegando a parte da lista "fam" apartir do sexto elemento até o oitavo, observando que a contagem dos elementos começa a partir do número 0. 
fam[6:8]

['Gabriela', 1.55]

In [478]:
fam[2:4]

['Cristiane', 1.65]

In [479]:
fam[4:6]

['Dulce', 1.3]

In [480]:
# Pegando do quarto elemento até o final da lista "fam"
fam[4:]

['Dulce', 1.3, 'Gabriela', 1.55]

In [481]:
# "Printando" o segundo elemento da lista de áreas
print(áreas[2])

kitchen


In [482]:
# "Printando" o ultimo elemento usando o index negativo
print(áreas[-1])

9.5


In [483]:
# "Printando" o valor de "living room"
print(áreas[4])

living room


**QUARTA AULA - 29\03**

In [484]:
# Somando os valores dos elementos 3 e 5 da lista "áreas" e atribuindo o resultado a uma variável.
eat_sleep_area = áreas[3] + áreas[5]

In [485]:
print(eat_sleep_area)

38.0


In [486]:
# Acessando os seis primeiros elementos da lista "àreas".
áreas = 'hallway', hall, 'kitchen', kit, 'living room', liv, 'bedroom', bed, 'bathroom', bath
print(áreas[:6])

('hallway', 14.0, 'kitchen', 18.0, 'living room', 20.0)


In [487]:
# Atribuindo os seis primeiros elementos da lista "áreas" a uma variável.
downstairs = áreas[:6]

In [488]:
# "Printando" do sexto elemento ao ultimo elemento da lista "áreas".
print(áreas[6:])

('bedroom', 10.75, 'bathroom', 9.5)


In [489]:
# Atribuindoo do sexto elemento ao ultimo elemento da lista "áreas" para uma variável.
upstairs = áreas[6:]

In [490]:
print(downstairs)
print(upstairs)

('hallway', 14.0, 'kitchen', 18.0, 'living room', 20.0)
('bedroom', 10.75, 'bathroom', 9.5)


In [491]:
# Mostrando elementos de uma lista que está dentro de uma lista.
x = [['a', 'b', 'c'],
     ["d","e","f"],
     ["g","h","i"]]
# O primeiro número entre colchetes é o número da lista, o segundo número entre colchetes se trata do número do elemento dentro da lista designada pelo o número anterior.
x[2][0]
x[2][:2]

['g', 'h']

In [492]:
house[-1][1]

9.5

In [493]:
# Mostrando a lista "fam"
print(fam)

['Pedro', 1.7, 'Cristiane', 1.65, 'Dulce', 1.3, 'Gabriela', 1.55]


In [494]:
# Motificando o elemento 7 da lista "fam" e atribuindo o novo valor de 1.65. 
fam[7] = 1.65
print(fam)

['Pedro', 1.7, 'Cristiane', 1.65, 'Dulce', 1.3, 'Gabriela', 1.65]


In [495]:
# O mesmo pode ser feito em intervalos maiores, como no exemplo a seguir: do primeiro elemento (0) ao terceiro elemento (2) será motificado, sendo atribuido um novo valor para esses elementos.
fam[0:2] = 'Vinicius', 1.75
print(fam)

['Vinicius', 1.75, 'Cristiane', 1.65, 'Dulce', 1.3, 'Gabriela', 1.65]


In [496]:
# Adicionando elementos em uma lista já existente.
fam + ["Maciel", 1.65]

['Vinicius',
 1.75,
 'Cristiane',
 1.65,
 'Dulce',
 1.3,
 'Gabriela',
 1.65,
 'Maciel',
 1.65]

In [497]:
# Adcionando uma extenção em uma lista.
fam_ext = fam + ["Maciel", 1.65]
# Excluindo o primeiro elemento (0) da lista "fam".
del(fam[0])
fam

[1.75, 'Cristiane', 1.65, 'Dulce', 1.3, 'Gabriela', 1.65]

In [498]:
# Mostrando o valor da nova varíavel.
print(fam_ext)

['Vinicius', 1.75, 'Cristiane', 1.65, 'Dulce', 1.3, 'Gabriela', 1.65, 'Maciel', 1.65]


In [499]:
# Variável "y" recebendo a variável "x" como valor. Nesse caso, "x" e "y" são a mesma coisa, isso quer dizer que o que acontecer com uma acontece também coma outra.
x = ["a", "b", "c"]
y = x
y[1] = "z"
print(y)

['a', 'z', 'c']


In [500]:
print(x)

['a', 'z', 'c']


In [501]:
# Para criar uma cópia de da lista que está na variável "x" é possível utilizar os seguintes comandos:
x = ["a","b","c"]
y = list(x)
print(y)

['a', 'b', 'c']


In [502]:
# ou
y = x[:]
print(y)

['a', 'b', 'c']


In [503]:
y[1] = "z"
# Nesses casos, a variável "y", que recebe a cópia do valor de x, ou seja, a lista, é distinta da varíavel "x", portanto, o que acontece com uma variável se limita apenas a mesma, não afetando a outra outra varível.
print(y)
print(x)

['a', 'z', 'c']
['a', 'b', 'c']


In [504]:
# Motificando o nono elemento da lista "áreas" e atribuindo-o um novo valor.
áreas = ['hallway', 14.0, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]
áreas[9] = 10.50
print(áreas)

['hallway', 14.0, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [505]:
# Motificando a string "living room" para "chill zone".
áreas[4] = 'chill zone'
print(áreas)

['hallway', 14.0, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [506]:
# Adicionando novos elementos em uma lista já existente e, criando uma nova lista com a lista modificada.
áreas + ['poolhouse', 24.5]
áreas_1 = áreas + ['poolhouse', 24.5]
print(áreas)
print(áreas_1)

['hallway', 14.0, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 14.0, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]


In [507]:
# Adicionando novamente novos elementos a uma lista e, novamente, criando uma nova lista com a lista modificada.
áreas_1 + ['garage', 15.5]
áreas_2 = áreas_1 + ['garage', 15.5]
print(áreas_1)
print(áreas_2)

['hallway', 14.0, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 14.0, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.5]


In [508]:
# Maneira errada de se criar uma cópia de uma lista. Nesse caso, a variável "áreas_copy" não cria uma cópia, mas sim é recebe em como valor a lista "áreas", tornando-se a mesma coisa.
áreas = [11.25, 18.0, 20.0, 10.75, 9.5]
áreas_copy = áreas
áreas_copy[0] = 5.0
print(áreas)

[5.0, 18.0, 20.0, 10.75, 9.5]


In [509]:
# Maneira correta de se criar uma cópia de uma lista. Nesse caso, é usado o comando que cria uma lista com o mesmo valor de outra, porém, não há qualquer vínculo com a lista copiada.
áreas = [11.25, 18.0, 20.0, 10.75, 9.5]
áreas_copy = list(áreas)
áreas_copy[0] = 5.0
print(áreas)
print(áreas_copy)

[11.25, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]


**QUINTA AULA - 03\04**

In [510]:
fam = [1.73, 1.68, 1.71, 1.89]

In [511]:
# Utilizando a função "max". Essa função é utilizada para mostrar o elemento de maior valor de uma lista.
max(fam)

1.89

In [512]:
# A função "round" é utilizada para arredondar um número. Nesse caso, o número "1" após o primeiro número signfica que o número que será arredondado aceitará uma casa decimal.
round(1.68, 1)

1.7

In [513]:
round(1.68)

2

In [514]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [515]:
# Criando duas variáveis: var1 e var2.
var1 = [1, 2, 3, 4]
var2 = True
# Mostrando o tipo de var1 utilizando o comando "type" junto com o comando "print".
print(type(var1))
# Mostrando a quantidade de elementos dentro de var2 utilizando a função "len"
print(len(var1))
# Convertendo o tipo de "var2" para "int" e atribuindo o novo valor em uma variável.
out2 = int(var2)
# Mostrando a nova variável.
print(out2)

<class 'list'>
4
1


In [516]:
#
first = [11.25, 18.0, 20.0, 10.75, 9.50]
second = [10.75, 9.50]
#
full = first + second
print(full)
#
full_sorted = sorted(full, reverse = True)
#
print(full_sorted)

[11.25, 18.0, 20.0, 10.75, 9.5, 10.75, 9.5]
[20.0, 18.0, 11.25, 10.75, 10.75, 9.5, 9.5]


In [517]:
#
lista_de_alimentos_com_preco = ['arroz', 7.0,
                                'feijão', 10.0,
                                'macarrão', 5.0,
                                'picanha', 70.0,
                                'linguiça', 25.0,
                                'frango', 30.0,
                                'tomate', 3.50,
                                'alface', 5.0,
                                'cebola', 3.50,
                                'suco de laranja', 6.0]

In [518]:
#
lista_de_alimentos_com_preco.index('picanha')

6

In [519]:
#
lista_de_alimentos_com_preco.count(3.50)

2

In [520]:
#
lista_de_alimentos_com_preco.append('cervejinha')
lista_de_alimentos_com_preco.append(50.0)
print(lista_de_alimentos_com_preco)

['arroz', 7.0, 'feijão', 10.0, 'macarrão', 5.0, 'picanha', 70.0, 'linguiça', 25.0, 'frango', 30.0, 'tomate', 3.5, 'alface', 5.0, 'cebola', 3.5, 'suco de laranja', 6.0, 'cervejinha', 50.0]


In [521]:
sister = "Dulce"

In [522]:
#
sister.capitalize()

'Dulce'

In [523]:
#
sister.replace("ulce","oce")

'Doce'

In [524]:
#
place = "poolhouse"
#
place_up = place.upper()
#
print(place)
print(place_up)
#
place.count('o')

poolhouse
POOLHOUSE


3

In [525]:
#
áreas = [11.25, 18.0, 20.0, 10.75, 9.50]
#
print(áreas.index(20.0))

2


In [526]:
print(áreas.count(9.5))

1


**SEXTA AULA - 05/04**

In [527]:
pip list

Package                       Version
----------------------------- --------------------
absl-py                       1.4.0
alabaster                     0.7.13
albumentations                1.2.1
altair                        4.2.2
anyio                         3.6.2
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.15.1
astropy                       5.2.2
astunparse                    1.6.3
attrs                         22.2.0
audioread                     3.0.0
autograd                      1.5
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.11.2
bleach                        6.0.0
blis                          0.7.9
blosc2                        2.0.0
bokeh                         2.4.3
branca                        0.6.0
CacheControl                  0.12.11
cached-property               1.5.2
cachetools                    5.3.0
cata

In [528]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [529]:
pip install pydicom

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [536]:
import numpy

In [535]:
array([1, 2, 3])

NameError: ignored

In [537]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [538]:
import numpy as np

In [539]:
np.array([1, 2, 3])

array([1, 2, 3])

In [540]:
from numpy import array

In [541]:
array([1, 2, 3])

array([1, 2, 3])

In [542]:
import numpy as np
fam = ['Pedro', 1.70, 'Cristiane', 1.65, 'Dulce', 1.30, 'Gabriela', 1.55]

fam_ext = fam + ["Maciel", 1.70]

print(str(len(fam_ext)) + " elements in fam_ext")

10 elements in fam_ext


In [543]:
np_fam = np.array(fam_ext)
print(type(fam_ext))
print(type(np_fam))

<class 'list'>
<class 'numpy.ndarray'>


In [544]:
r = 0.43

import math

C = 2 * math.pi * r

A = math.pi * r ** 2

print("Circumference: " + str(C))
print("Área: " + str(A)) 

Circumference: 2.701769682087222
Área: 0.5808804816487527


In [545]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [546]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [ ]:
weight / height ** 2

In [549]:
import numpy as np
np_height = np.array(height)
print(np_height)

[1.73 1.68 1.71 1.89 1.79]


In [550]:
np_weight = np.array(weight)
print(np_weight)

[65.4 59.2 63.6 88.4 68.7]


In [551]:
bmi = np_weight / np_height ** 2
print(bmi)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


In [552]:
pyton_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [553]:
pyton_list + pyton_list

[1, 2, 3, 1, 2, 3]

In [554]:
numpy_array + numpy_array

array([2, 4, 6])

In [555]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [556]:
bmi[1]

20.97505668934241

In [557]:
bmi > 23

array([False, False, False,  True, False])

In [558]:
bmi[bmi > 23]

array([24.7473475])

**SÉTIMA AULA - 10/04**

In [561]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 69.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 69.7 ]])

In [562]:
np_2d.shape

(2, 5)

In [563]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
         [65.4, 59.2, 63.6, 88.4, '69.7']])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '69.7']], dtype='<U32')

In [565]:
np_2d = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_2d

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [572]:
np1_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 69.7],
                  [25.1, 22.2, 18.3, 35.4, 23.5]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 69.7 ],
       [25.1 , 22.2 , 18.3 , 35.4 , 23.5 ]])

In [573]:
np2_2d = np.array([[1.73, 1.68, 1.71],
                  [65.4, 59.2, 63.6],
                  [25.1, 22.2, 18.3]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 69.7 ],
       [25.1 , 22.2 , 18.3 , 35.4 , 23.5 ]])

In [576]:
np_2d[0][2]

1.71

In [577]:
np_2d[0,2]

1.71

In [578]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ],
       [22.2 , 18.3 ]])

In [579]:
np_2d[1,:]

array([65.4, 59.2, 63.6, 88.4, 69.7])

In [585]:
#
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
#
import numpy
#
np_baseball = np.array(baseball)
#
print(type(np_baseball))
#
print(np_baseball.shape)

<class 'numpy.ndarray'>
(8,)


In [603]:
import random as rd
import numpy as np
#
height = range(150,210)
#
weight = range(50,149)
#
height = rd.sample(height,20)
#
weight = rd.sample(weight,20)
#
height_array = np.array(height) * 0.01
#
weight_array = np.array(weight)
#
bmi = weight_array / height_array ** 2
#
light = bmi < 21
#
print(light)
#
print(bmi[bmi < 21])
#
print(weight_array[8:16])
#
print(height_array[11:20])

[False  True False False False False  True False False False  True False
  True False False False False  True False False]
[17.61772522 18.74219075 16.27604167 16.83103222 20.95717116]
[133 130  60  85  64 109 126 100]
[1.89 1.95 1.64 1.6  1.55 1.53 1.62 1.77 1.76]


In [624]:
#
baseball = [[180, 78.4],
           [215, 102.7],
           [210, 98.5],
           [188, 75.2]]
#
import numpy as np
#
np_baseball = np.array(baseball)
#
print(np_baseball[2,])
#
np_weight_lb = np_baseball[:,1]
#
print(np_baseball[1,1])
#
print(np.mean(np_baseball[:,0]))
#
print(np.median(np_baseball[1,:]))

[210.   98.5]
102.7
198.25
158.85
